HEADERS += \
    vcprojectmodel/vcprojectdocument_constants.h \
    vcprojectmodel/vcprojectdocument.h \
    vcprojectmodel/toolfiles.h \
    vcprojectmodel/toolfile.h \
    vcprojectmodel/references.h \
    vcprojectmodel/publishingitem.h \
    vcprojectmodel/publishingdata.h \
    vcprojectmodel/projectreference.h \
    vcprojectmodel/platforms.h \
    vcprojectmodel/platform.h \
    vcprojectmodel/globals.h \
    vcprojectmodel/global.h \
    vcprojectmodel/files.h \
    vcprojectmodel/file.h \
    vcprojectmodel/deploymenttool.h \
    vcprojectmodel/defaulttoolfile.h \
    vcprojectmodel/debuggertool.h \
    vcprojectmodel/configurations.h \
    vcprojectmodel/configuration.h \
    vcprojectmodel/assemblyreference.h \
    vcprojectmodel/activexreference.h \
    vcprojectmodel/tools/tool_constants.h \
    vcprojectmodel/tools/candcpptool_constants.h \
    vcprojectmodel/vcdocumentmodel.h \
    vcprojectmodel/vcdocprojectnodes.h \
    vcprojectmodel/tools/toolattributes/booltoolattribute.h \
    vcprojectmodel/tools/toolattributes/stringtoolattribute.h \
    vcprojectmodel/tools/toolattributes/stringlisttoolattribute.h \
    vcprojectmodel/tools/toolattributes/integertoolattribute.h \
    vcprojectmodel/tools/configurationtool.h \
    vcprojectmodel/tools/toolattributes/tooldescriptiondatamanager.h \
    vcprojectmodel/tools/toolattributes/tooldescription.h \
    vcprojectmodel/tools/toolattributes/iattributedescriptiondataitem.h \
    vcprojectmodel/tools/toolsectiondescription.h \
    vcprojectmodel/tools/toolsection.h \
    vcprojectmodel/tools/toolattributes/toolattributeoption.h \
    vcprojectmodel/tools/toolattributes/attributedescriptiondataitem.h \
    vcprojectmodel/generalattributecontainer.h \
    vcprojectmodel/tools/toolattributes/toolsectioncontainer.h \
    vcprojectmodel/configurationcontainer.h \
    vcprojectmodel/tools/generaltoolattributecontainer.h \
    vcprojectmodel/configurationbuildtools.h \
    vcprojectmodel/deploymenttools.h \
    vcprojectmodel/tools.h \
    vcprojectmodel/debuggertools.h \
    vcprojectmodel/filecontainer.h

SOURCES += \
    vcprojectmodel/vcprojectdocument.cpp \
    vcprojectmodel/toolfiles.cpp \
    vcprojectmodel/toolfile.cpp \
    vcprojectmodel/references.cpp \
    vcprojectmodel/publishingitem.cpp \
    vcprojectmodel/publishingdata.cpp \
    vcprojectmodel/projectreference.cpp \
    vcprojectmodel/platforms.cpp \
    vcprojectmodel/platform.cpp \
    vcprojectmodel/globals.cpp \
    vcprojectmodel/global.cpp \
    vcprojectmodel/files.cpp \
    vcprojectmodel/file.cpp \
    vcprojectmodel/deploymenttool.cpp \
    vcprojectmodel/defaulttoolfile.cpp \
    vcprojectmodel/debuggertool.cpp \
    vcprojectmodel/configurations.cpp \
    vcprojectmodel/configuration.cpp \
    vcprojectmodel/assemblyreference.cpp \
    vcprojectmodel/activexreference.cpp \
    vcprojectmodel/vcdocumentmodel.cpp \
    vcprojectmodel/ivcprojectnodemodel.cpp \
    vcprojectmodel/vcdocprojectnodes.cpp \
    vcprojectmodel/tools/toolattributes/booltoolattribute.cpp \
    vcprojectmodel/tools/toolattributes/stringtoolattribute.cpp \
    vcprojectmodel/tools/toolattributes/stringlisttoolattribute.cpp \
    vcprojectmodel/tools/toolattributes/integertoolattribute.cpp \
    vcprojectmodel/tools/configurationtool.cpp \
    vcprojectmodel/tools/toolattributes/tooldescriptiondatamanager.cpp \
    vcprojectmodel/tools/toolattributes/tooldescription.cpp \
    vcprojectmodel/tools/toolsectiondescription.cpp \
    vcprojectmodel/tools/toolsection.cpp \
    vcprojectmodel/tools/toolattributes/toolattributeoption.cpp \
    vcprojectmodel/tools/toolattributes/attributedescriptiondataitem.cpp \
    vcprojectmodel/generalattributecontainer.cpp \
    vcprojectmodel/tools/toolattributes/toolsectioncontainer.cpp \
    vcprojectmodel/configurationcontainer.cpp \
    vcprojectmodel/tools/generaltoolattributecontainer.cpp \
    vcprojectmodel/configurationbuildtools.cpp \
    vcprojectmodel/deploymenttools.cpp \
    vcprojectmodel/tools.cpp \
    vcprojectmodel/debuggertools.cpp \
    vcprojectmodel/filecontainer.cpp

OTHER_FILES += \
    vcprojectmodel/tools/xml_definitions/VCXMLDataGeneratorTool.xml \
    vcprojectmodel/tools/xml_definitions/VCXDCMakeTool.xml \
    vcprojectmodel/tools/xml_definitions/VCWebServiceProxyGeneratorTool.xml \
    vcprojectmodel/tools/xml_definitions/VCResourceCompilerTool.xml \
    vcprojectmodel/tools/xml_definitions/VCPreLinkEventTool.xml \
    vcprojectmodel/tools/xml_definitions/VcPreBuildEventTool.xml \
    vcprojectmodel/tools/xml_definitions/VCPostBuildEventTool.xml \
    vcprojectmodel/tools/xml_definitions/VCMIDLTool.xml \
    vcprojectmodel/tools/xml_definitions/VCManifestTool.xml \
    vcprojectmodel/tools/xml_definitions/VCManagedResourceCompilerTool.xml \
    vcprojectmodel/tools/xml_definitions/VCLinkerTool.xml \
    vcprojectmodel/tools/xml_definitions/VCCustomBuildTool.xml \
    vcprojectmodel/tools/xml_definitions/VCCLCompilerTool.xml \
    vcprojectmodel/tools/xml_definitions/VCBscMakeTool.xml
