HEADERS += \
    vcprojectmodel/vcprojectdocument_constants.h \
    vcprojectmodel/vcprojectdocument.h \
    vcprojectmodel/toolfiles.h \
    vcprojectmodel/toolfile.h \
    vcprojectmodel/references.h \
    vcprojectmodel/publishingitem.h \
    vcprojectmodel/publishingdata.h \
    vcprojectmodel/projectreference_private.h \
    vcprojectmodel/projectreference.h \
    vcprojectmodel/platforms.h \
    vcprojectmodel/platform.h \
    vcprojectmodel/globals.h \
    vcprojectmodel/global.h \
    vcprojectmodel/folder.h \
    vcprojectmodel/filter.h \
    vcprojectmodel/files.h \
    vcprojectmodel/file.h \
    vcprojectmodel/deploymenttool.h \
    vcprojectmodel/defaulttoolfile.h \
    vcprojectmodel/debuggertool.h \
    vcprojectmodel/configurationsfactory.h \
    vcprojectmodel/configurations.h \
    vcprojectmodel/configuration.h \
    vcprojectmodel/assemblyreference.h \
    vcprojectmodel/activexreference.h \
    vcprojectmodel/tools/xmldocgeneratortool.h \
    vcprojectmodel/tools/toolfactory.h \
    vcprojectmodel/tools/tool_constants.h \
    vcprojectmodel/tools/tool.h \
    vcprojectmodel/tools/prelinkeventtool.h \
    vcprojectmodel/tools/prebuildeventtool.h \
    vcprojectmodel/tools/postbuildeventtool.h \
    vcprojectmodel/tools/manifesttool.h \
    vcprojectmodel/tools/linkertool.h \
    vcprojectmodel/tools/linker_constants.h \
    vcprojectmodel/tools/generaltool.h \
    vcprojectmodel/tools/custombuildsteptool.h \
    vcprojectmodel/tools/candcpptool_constants.h \
    vcprojectmodel/tools/candcpptool.h \
    vcprojectmodel/tools/browseinformationtool.h \
    vcprojectmodel/vcdocumentmodel.h \
    vcprojectmodel/ivcprojectnodemodel.h \
    vcprojectmodel/vcdocprojectnodes.h

SOURCES += \
    vcprojectmodel/vcprojectdocument.cpp \
    vcprojectmodel/toolfiles.cpp \
    vcprojectmodel/toolfile.cpp \
    vcprojectmodel/references.cpp \
    vcprojectmodel/publishingitem.cpp \
    vcprojectmodel/publishingdata.cpp \
    vcprojectmodel/projectreference_private.cpp \
    vcprojectmodel/projectreference.cpp \
    vcprojectmodel/platforms.cpp \
    vcprojectmodel/platform.cpp \
    vcprojectmodel/globals.cpp \
    vcprojectmodel/global.cpp \
    vcprojectmodel/folder.cpp \
    vcprojectmodel/filter.cpp \
    vcprojectmodel/files.cpp \
    vcprojectmodel/file.cpp \
    vcprojectmodel/deploymenttool.cpp \
    vcprojectmodel/defaulttoolfile.cpp \
    vcprojectmodel/debuggertool.cpp \
    vcprojectmodel/configurationsfactory.cpp \
    vcprojectmodel/configurations.cpp \
    vcprojectmodel/configuration.cpp \
    vcprojectmodel/assemblyreference.cpp \
    vcprojectmodel/activexreference.cpp \
    vcprojectmodel/tools/xmldocgeneratortool.cpp \
    vcprojectmodel/tools/toolfactory.cpp \
    vcprojectmodel/tools/tool.cpp \
    vcprojectmodel/tools/prelinkeventtool.cpp \
    vcprojectmodel/tools/prebuildeventtool.cpp \
    vcprojectmodel/tools/postbuildeventtool.cpp \
    vcprojectmodel/tools/manifesttool.cpp \
    vcprojectmodel/tools/linkertool.cpp \
    vcprojectmodel/tools/generaltool.cpp \
    vcprojectmodel/tools/custombuildsteptool.cpp \
    vcprojectmodel/tools/candcpptool.cpp \
    vcprojectmodel/tools/browseinformationtool.cpp \
    vcprojectmodel/vcdocumentmodel.cpp \
    vcprojectmodel/ivcprojectnodemodel.cpp \
    vcprojectmodel/vcdocprojectnodes.cpp
