include(qtsupport_dependencies.pri)

LIBS *= -l$$qtLibraryName(QtSupport)
DEFINES *= QMAKE_AS_LIBRARY
DEFINES *= PROPARSER_THREAD_SAFE
DEFINES *= PROEVALUATOR_THREAD_SAFE
DEFINES *= PROEVALUATOR_CUMULATIVE
