include(../../plugins/projectexplorer/projectexplorer.pri)
include(../../plugins/texteditor/texteditor.pri)
include(../../plugins/qmljseditor/qmljseditor.pri)
include(../../plugins/debugger/debugger.pri)
include(../../plugins/qt4projectmanager/qt4projectmanager.pri)
