include(../../plugins/projectexplorer/projectexplorer.pri)
include(../../plugins/texteditor/texteditor.pri)
include(../../plugins/qmljseditor/qmljseditor.pri)
include(../../plugins/qmljstools/qmljstools.pri)
include(../../plugins/debugger/debugger.pri)
include(../../plugins/qtsupport/qtsupport.pri)
