#ifndef QSCRIPTHIGHLIGHTER_GLOBAL_H
#define QSCRIPTHIGHLIGHTER_GLOBAL_H

#include <QtCore/QtGlobal>

#ifdef QSCRIPTHIGHLIGHTER_BUILD_LIB
#  define QSCRIPTHIGHLIGHTER_EXPORT Q_DECL_EXPORT
#else // !QSCRIPTHIGHLIGHTER
#  define QSCRIPTHIGHLIGHTER_EXPORT Q_DECL_IMPORT
#endif // QSCRIPTHIGHLIGHTER

#endif // QSCRIPTHIGHLIGHTER_GLOBAL_H
