QTCREATOR_VERSION = 4.10.84
QTCREATOR_COMPAT_VERSION = 4.10.84
QTCREATOR_DISPLAY_VERSION = 4.11.0-rc1
QTCREATOR_COPYRIGHT_YEAR = 2019
BINARY_ARTIFACTS_BRANCH = 4.11

IDE_DISPLAY_NAME = Qt Creator
IDE_ID = qtcreator
IDE_CASED_ID = QtCreator

PRODUCT_BUNDLE_ORGANIZATION = org.qt-project
PROJECT_USER_FILE_EXTENSION = .user
