// Copyright (C) The Qt Company Ltd. and other contributors.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists for the convenience
// of other Qt classes.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

// This file was generated by qlalr - DO NOT EDIT!
#ifndef CMAKEPARSERTABLE_P_H
#define CMAKEPARSERTABLE_P_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

class CMakeParserTable
{
public:
    enum VariousConstants {
        EOF_SYMBOL = 0,
        T_BLOCK = 26,
        T_BRACKET_ARGUMENT = 6,
        T_BRACKET_COMMENT = 10,
        T_COMMENT = 9,
        T_ELSE = 16,
        T_ELSEIF = 15,
        T_ENDBLOCK = 27,
        T_ENDFOREACH = 19,
        T_ENDFUNCTION = 23,
        T_ENDIF = 17,
        T_ENDMACRO = 25,
        T_ENDWHILE = 21,
        T_ERROR = 11,
        T_FOREACH = 18,
        T_FUNCTION = 22,
        T_IDENTIFIER = 1,
        T_IF = 14,
        T_LEFT_PAREN = 2,
        T_MACRO = 24,
        T_NEWLINE = 7,
        T_QUOTED_ARGUMENT = 5,
        T_RIGHT_PAREN = 3,
        T_SPACE = 8,
        T_UNQUOTED_ARGUMENT = 4,
        T_UNTERMINATED_BRACKET = 12,
        T_UNTERMINATED_STRING = 13,
        T_WHILE = 20,

        ACCEPT_STATE = 3,
        RULE_COUNT = 45,
        STATE_COUNT = 115,
        TERMINAL_COUNT = 28,
        NON_TERMINAL_COUNT = 30,

        GOTO_INDEX_OFFSET = 115,
        GOTO_INFO_OFFSET = 270,
        GOTO_CHECK_OFFSET = 270
    };

    static const char *const     spell[];
    static const short             lhs[];
    static const short             rhs[];
    static const short    goto_default[];
    static const short  action_default[];
    static const short    action_index[];
    static const short     action_info[];
    static const short    action_check[];

    static inline int nt_action (int state, int nt)
    {
        const int yyn = action_index [GOTO_INDEX_OFFSET + state] + nt;
        if (yyn < 0 || action_check [GOTO_CHECK_OFFSET + yyn] != nt)
            return goto_default [nt];

        return action_info [GOTO_INFO_OFFSET + yyn];
    }

    static inline int t_action (int state, int token)
    {
        const int yyn = action_index [state] + token;

        if (yyn < 0 || action_check [yyn] != token)
            return - action_default [state];

        return action_info [yyn];
    }
};


QT_END_NAMESPACE
#endif // CMAKEPARSERTABLE_P_H

