<tpa>
    <pluginName>CppEditor</pluginName>
    <author>Trolltech AS</author>
    <version>1.0</version>
    <extendsInterfaceList>
        <extendsInterface>
            <name>EditorFactoryInterface</name>
        </extendsInterface>
        <extendsInterface>
            <name>WizardInterface</name>
        </extendsInterface>
        <extendsInterface>
            <name>OptionsPageInterface</name>
        </extendsInterface>
    </extendsInterfaceList>
</tpa>
