import qbs

Project {
    name: "Utils autotests"
    references: [
        "ansiescapecodehandler/ansiescapecodehandler.qbs",
        "async/async.qbs",
        "commandline/commandline.qbs",
        "covariantcallback/covariantcallback.qbs",
        "dialogtask/dialogtask.qbs",
        "displayname/displayname.qbs",
        "elfreader/elfreader.qbs",
        "expander/expander.qbs",
        "expected/expected.qbs",
        "filepath/filepath.qbs",
        "fileinprojectfinder/fileinprojectfinder.qbs",
        "filesystemmodel/filesystemmodel.qbs",
        "fileutils/fileutils.qbs",
        "fsengine/fsengine.qbs",
        "fuzzymatcher/fuzzymatcher.qbs",
        "guiutils/guiutils.qbs",
        "id/id.qbs",
        "indexedcontainerproxyconstiterator/indexedcontainerproxyconstiterator.qbs",
        "markdown/markdown.qbs",
        "mathutils/mathutils.qbs",
        "multicursor/multicursor.qbs",
        "pathchooser/pathchooser.qbs",
        "persistentsettings/persistentsettings.qbs",
        "process/process.qbs",
        "settings/settings.qbs",
        "spellchecker/spellchecker.qbs",
        "stringutils/stringutils.qbs",
        "stylehelper/stylehelper.qbs",
        "synchronizedvalue/synchronizedvalue.qbs",
        "templateengine/templateengine.qbs",
        "terminalinterface/terminalinterface.qbs",
        "text/text.qbs",
        "theme/theme.qbs",
        "treemodel/treemodel.qbs",
        "unarchiver/unarchiver.qbs",
        "unixdevicefileaccess/unixdevicefileaccess.qbs",
    ]
}
