FROM ubuntu:25.10

RUN apt-get update && \
    apt-get install -y \
    libgl1-mesa-dev \
    qt6-base-dev \
    qt6-base-private-dev \
    qt6-declarative-dev \
    qt6-declarative-private-dev \
    libqt6core5compat6-dev \
    build-essential \
    cmake \
    nano \
    ninja-build \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    gdb \
    xterm \
    && rm -rf /var/lib/apt/lists/*
