
FROM ubuntu:24.04

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    openssh-client \
    sudo \
    vim \
    wget \
    qt6-base-dev \
    qt6-5compat-dev \
    gdb \
    linux-tools-common \
    valgrind \
    x11-apps \
    clangd \
    qbs
