#ifndef DUIEDITOR_GLOBAL_H
#define DUIEDITOR_GLOBAL_H

#include <QtGlobal>

#if defined(DUIEDITOR_LIBRARY)
#  define DUIEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define DUIEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // DUIEDITOR_GLOBAL_H
