include(../qttest.pri)
include($$IDE_SOURCE_TREE/src/libs/utils/utils.pri)

win32:DEFINES += _CRT_SECURE_NO_WARNINGS

SOURCES +=  tst_qtcprocess.cpp 

DEFINES -= QT_USE_FAST_CONCATENATION QT_USE_FAST_OPERATOR_PLUS
DEFINES -= QT_NO_CAST_TO_ASCII QT_NO_CAST_FROM_ASCII
