######################################################################
# Automatically generated by qmake (2.01a) Fr Jul 27 23:12:52 2007
######################################################################

TARGET = pluginmanager

# Input

include(../../../../../../tests/auto/qttest.pri)
include(../../../extensionsystem.pri)

SOURCES += tst_pluginmanager.cpp

OTHER_FILES = $$PWD/plugins/otherplugin.xml \
    $$PWD/plugins/plugin1.xml \
    $$PWD/plugins/myplug/myplug.xml

COPYDIR = $$OUT_PWD
COPYFILES = $$OTHER_FILES
include(../copy.pri)
