######################################################################
# Automatically generated by qmake (2.01a) Fr Jul 27 23:12:52 2007
######################################################################

CONFIG += qtestlib
TEMPLATE = app
CONFIG -= app_bundle

# Input

include(../../extensionsystem_test.pri)

SOURCES += tst_pluginmanager.cpp

