include(../../plugins/coreplugin/coreplugin.pri)
include(../../plugins/analyzerbase/analyzerbase.pri)
include(../../plugins/qmlprojectmanager/qmlprojectmanager.pri)
include(../../plugins/qt4projectmanager/qt4projectmanager.pri)
include(../../plugins/qmljstools/qmljstools.pri)
include(../../plugins/remotelinux/remotelinux.pri)
include(../../libs/qmldebug/qmldebug.pri)
include(../../libs/extensionsystem/extensionsystem.pri)
