#ifndef QMLPROFILERPLUGIN_GLOBAL_H
#define QMLPROFILERPLUGIN_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(QMLPROFILERPLUGIN_LIBRARY)
#  define QMLPROFILERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMLPROFILERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMLPROFILERPLUGIN_GLOBAL_H

