#ifndef ICHECKLIB_GLOBAL_H
#define ICHECKLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ICHECKLIB_LIBRARY)
#  define ICHECKLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ICHECKLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ICHECKLIB_GLOBAL_H
