/*
  This file was generated by the Html5 Application wizard of Qt Creator.
  Html5ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef WEBNAVIGATION_H
#define WEBNAVIGATION_H

#include <QObject>

class QWebPage;
class WebTouchNavigation;

class WebNavigation : public QObject
{
    Q_OBJECT

public:
    WebNavigation(QObject *parent, QWebPage *webPage);
    virtual ~WebNavigation();

private:
    QObject *m_viewObject;
    QWebPage *m_webPage;
    WebTouchNavigation *m_webTouchNavigation;
};

#endif // WEBNAVIGATION_H
