/*
  This file was generated by the Html5 Application wizard of Qt Creator.
  Html5ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef WEBTOUCHEVENT_H
#define WEBTOUCHEVENT_H

#include <QEvent>
#include <QGraphicsSceneMouseEvent>
#include <QMouseEvent>
#include <QPoint>

class WebTouchEvent
{
public:
    WebTouchEvent();
    WebTouchEvent(const QMouseEvent *mouseEvent);
    WebTouchEvent(const QGraphicsSceneMouseEvent *graphicsSceneMouseEvent);

    QPoint m_pos;
    QEvent::Type m_type;
    Qt::MouseButton m_button;
    Qt::MouseButtons m_buttons;
    bool m_graphicsSceneEvent;
    bool m_fired;
    bool m_editable;
    Qt::KeyboardModifiers m_modifier;

    //Graphics scene event members
    QPointF m_scenePos;
    QPoint m_screenPos;
    QPointF m_buttonDownPos;
    QPointF m_buttonDownScenePos;
    QPoint m_buttonDownScreenPos;
    QPointF m_lastPos;
    QPointF m_lastScenePos;
    QPoint m_lastScreenPos;
};

#endif // WEBTOUCHEVENT_H
