######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 6 12:55:36 2009
######################################################################

VPATH += $$PWD
INCLUDEPATH += $$PWD

# Input
HEADERS += itemlibrary.h itemlibrarymodel.h customdraganddrop.h
FORMS += itemlibrary.ui
SOURCES += itemlibrary.cpp itemlibrarymodel.cpp customdraganddrop.cpp
RESOURCES += itemlibrary.qrc
