######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 6 12:55:36 2009
######################################################################

VPATH += $$PWD
INCLUDEPATH += $$PWD

# Input
HEADERS += itemlibrary.h customdraganddrop.h itemlibrarymodel.h itemlibrarywidgets.h
FORMS += itemlibrary.ui
SOURCES += itemlibrary.cpp customdraganddrop.cpp itemlibrarymodel.cpp itemlibrarywidgets.cpp
RESOURCES += itemlibrary.qrc

