include(../../plugins/coreplugin/coreplugin.pri)
include(../../plugins/texteditor/texteditor.pri)
include(../../plugins/help/help.pri)
include(../../shared/indenter/indenter.pri)
include(../../libs/qml/qml.pri)
include(../../libs/utils/utils.pri)
