include(../../plugins/coreplugin/coreplugin.pri)
include(../../libs/cplusplus/cplusplus.pri)
include(../../plugins/projectexplorer/projectexplorer.pri)
include(../../plugins/remotelinux/remotelinux.pri)
include(../../plugins/cpptools/cpptools.pri)
