include(../../libs/utils/utils.pri)
include(../../plugins/locator/locator.pri)
include(../../plugins/find/find.pri)
include(../../plugins/coreplugin/coreplugin.pri)
include(../../plugins/texteditor/texteditor.pri)
