// Copyright (C) 2023 The Qt Company Ltd and other contributors.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists for the convenience
// of other Qt classes.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

// This file was generated by qlalr - DO NOT EDIT!
#ifndef GLSLPARSERTABLE_P_H
#define GLSLPARSERTABLE_P_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

class GLSLParserTable
{
public:
    enum VariousConstants {
        EOF_SYMBOL = 0,
        T_ADD_ASSIGN = 3,
        T_AMPERSAND = 4,
        T_AND_ASSIGN = 5,
        T_AND_OP = 6,
        T_ATOMIC_UINT = 7,
        T_ATTRIBUTE = 8,
        T_BANG = 9,
        T_BOOL = 10,
        T_BREAK = 11,
        T_BUFFER = 15,
        T_BVEC2 = 12,
        T_BVEC3 = 13,
        T_BVEC4 = 14,
        T_CARET = 16,
        T_CASE = 17,
        T_CENTROID = 18,
        T_COHERENT = 19,
        T_COLON = 20,
        T_COMMA = 21,
        T_COMMENT = 214,
        T_CONST = 22,
        T_CONTINUE = 23,
        T_DASH = 24,
        T_DEC_OP = 25,
        T_DEFAULT = 26,
        T_DISCARD = 27,
        T_DIV_ASSIGN = 28,
        T_DMAT2 = 29,
        T_DMAT2X2 = 30,
        T_DMAT2X3 = 31,
        T_DMAT2X4 = 32,
        T_DMAT3 = 33,
        T_DMAT3X2 = 34,
        T_DMAT3X3 = 35,
        T_DMAT3X4 = 36,
        T_DMAT4 = 37,
        T_DMAT4X2 = 38,
        T_DMAT4X3 = 39,
        T_DMAT4X4 = 40,
        T_DO = 41,
        T_DOT = 42,
        T_DOUBLE = 43,
        T_DVEC2 = 44,
        T_DVEC3 = 45,
        T_DVEC4 = 46,
        T_ELSE = 47,
        T_EQUAL = 48,
        T_EQ_OP = 49,
        T_ERROR = 215,
        T_FALSE = 212,
        T_FEED_EXPRESSION = 2,
        T_FEED_GLSL = 1,
        T_FLAT = 50,
        T_FLOAT = 51,
        T_FOR = 52,
        T_GE_OP = 53,
        T_HIGHP = 54,
        T_IDENTIFIER = 55,
        T_IF = 56,
        T_IIMAGE1D = 57,
        T_IIMAGE1DARRAY = 58,
        T_IIMAGE2D = 59,
        T_IIMAGE2DARRAY = 60,
        T_IIMAGE2DMS = 61,
        T_IIMAGE2DMSARRAY = 62,
        T_IIMAGE2DRECT = 63,
        T_IIMAGE3D = 64,
        T_IIMAGEBUFFER = 65,
        T_IIMAGECUBE = 66,
        T_IIMAGECUBEARRAY = 67,
        T_IMAGE1D = 68,
        T_IMAGE1DARRAY = 69,
        T_IMAGE2D = 70,
        T_IMAGE2DARRAY = 71,
        T_IMAGE2DMS = 72,
        T_IMAGE2DMSARRAY = 73,
        T_IMAGE2DRECT = 74,
        T_IMAGE3D = 75,
        T_IMAGEBUFFER = 76,
        T_IMAGECUBE = 77,
        T_IMAGECUBEARRAY = 78,
        T_IN = 79,
        T_INC_OP = 80,
        T_INOUT = 81,
        T_INT = 82,
        T_INVARIANT = 83,
        T_ISAMPLER1D = 84,
        T_ISAMPLER1DARRAY = 85,
        T_ISAMPLER2D = 86,
        T_ISAMPLER2DARRAY = 87,
        T_ISAMPLER2DMS = 88,
        T_ISAMPLER2DMSARRAY = 89,
        T_ISAMPLER2DRECT = 90,
        T_ISAMPLER3D = 91,
        T_ISAMPLERBUFFER = 92,
        T_ISAMPLERCUBE = 93,
        T_ISAMPLERCUBEARRAY = 94,
        T_IVEC2 = 95,
        T_IVEC3 = 96,
        T_IVEC4 = 97,
        T_LAYOUT = 98,
        T_LEFT_ANGLE = 99,
        T_LEFT_ASSIGN = 100,
        T_LEFT_BRACE = 101,
        T_LEFT_BRACKET = 102,
        T_LEFT_OP = 103,
        T_LEFT_PAREN = 104,
        T_LE_OP = 105,
        T_LOWP = 106,
        T_MAT2 = 107,
        T_MAT2X2 = 108,
        T_MAT2X3 = 109,
        T_MAT2X4 = 110,
        T_MAT3 = 111,
        T_MAT3X2 = 112,
        T_MAT3X3 = 113,
        T_MAT3X4 = 114,
        T_MAT4 = 115,
        T_MAT4X2 = 116,
        T_MAT4X3 = 117,
        T_MAT4X4 = 118,
        T_MEDIUMP = 119,
        T_MOD_ASSIGN = 120,
        T_MUL_ASSIGN = 121,
        T_NE_OP = 122,
        T_NOPERSPECTIVE = 123,
        T_NUMBER = 124,
        T_OR_ASSIGN = 125,
        T_OR_OP = 126,
        T_OUT = 127,
        T_PATCH = 128,
        T_PERCENT = 129,
        T_PLUS = 130,
        T_PRECISE = 131,
        T_PRECISION = 132,
        T_PREPROC = 213,
        T_QUESTION = 133,
        T_READONLY = 134,
        T_RESERVED = 216,
        T_RESTRICT = 135,
        T_RETURN = 136,
        T_RIGHT_ANGLE = 137,
        T_RIGHT_ASSIGN = 138,
        T_RIGHT_BRACE = 139,
        T_RIGHT_BRACKET = 140,
        T_RIGHT_OP = 141,
        T_RIGHT_PAREN = 142,
        T_SAMPLE = 143,
        T_SAMPLER1D = 144,
        T_SAMPLER1DARRAY = 145,
        T_SAMPLER1DARRAYSHADOW = 146,
        T_SAMPLER1DSHADOW = 147,
        T_SAMPLER2D = 148,
        T_SAMPLER2DARRAY = 149,
        T_SAMPLER2DARRAYSHADOW = 150,
        T_SAMPLER2DMS = 151,
        T_SAMPLER2DMSARRAY = 152,
        T_SAMPLER2DRECT = 153,
        T_SAMPLER2DRECTSHADOW = 154,
        T_SAMPLER2DSHADOW = 155,
        T_SAMPLER3D = 156,
        T_SAMPLERBUFFER = 157,
        T_SAMPLERCUBE = 158,
        T_SAMPLERCUBEARRAY = 159,
        T_SAMPLERCUBEARRAYSHADOW = 160,
        T_SAMPLERCUBESHADOW = 161,
        T_SEMICOLON = 162,
        T_SHARED = 163,
        T_SLASH = 164,
        T_SMOOTH = 165,
        T_STAR = 166,
        T_STRUCT = 167,
        T_SUBROUTINE = 168,
        T_SUB_ASSIGN = 169,
        T_SWITCH = 170,
        T_TILDE = 171,
        T_TRUE = 211,
        T_TYPE_NAME = 172,
        T_UIMAGE1D = 173,
        T_UIMAGE1DARRAY = 174,
        T_UIMAGE2D = 175,
        T_UIMAGE2DARRAY = 176,
        T_UIMAGE2DMS = 177,
        T_UIMAGE2DMSARRAY = 178,
        T_UIMAGE2DRECT = 179,
        T_UIMAGE3D = 180,
        T_UIMAGEBUFFER = 181,
        T_UIMAGECUBE = 182,
        T_UIMAGECUBEARRAY = 183,
        T_UINT = 184,
        T_UNIFORM = 185,
        T_USAMPLER1D = 186,
        T_USAMPLER1DARRAY = 187,
        T_USAMPLER2D = 188,
        T_USAMPLER2DARRAY = 189,
        T_USAMPLER2DMS = 190,
        T_USAMPLER2DMSARRAY = 191,
        T_USAMPLER2DRECT = 192,
        T_USAMPLER3D = 193,
        T_USAMPLERBUFFER = 194,
        T_USAMPLERCUBE = 195,
        T_USAMPLERCUBEARRAY = 196,
        T_UVEC2 = 197,
        T_UVEC3 = 198,
        T_UVEC4 = 199,
        T_VARYING = 200,
        T_VEC2 = 201,
        T_VEC3 = 202,
        T_VEC4 = 203,
        T_VERTICAL_BAR = 204,
        T_VOID = 205,
        T_VOLATILE = 206,
        T_WHILE = 207,
        T_WRITEONLY = 208,
        T_XOR_ASSIGN = 209,
        T_XOR_OP = 210,

        ACCEPT_STATE = 508,
        RULE_COUNT = 371,
        STATE_COUNT = 509,
        TERMINAL_COUNT = 217,
        NON_TERMINAL_COUNT = 91,

        GOTO_INDEX_OFFSET = 509,
        GOTO_INFO_OFFSET = 5487,
        GOTO_CHECK_OFFSET = 5487
    };

    static const char *const     spell[];
    static const short             lhs[];
    static const short             rhs[];
    static const short    goto_default[];
    static const short  action_default[];
    static const short    action_index[];
    static const short     action_info[];
    static const short    action_check[];

    static inline int nt_action (int state, int nt)
    {
        const int yyn = action_index [GOTO_INDEX_OFFSET + state] + nt;
        if (yyn < 0 || action_check [GOTO_CHECK_OFFSET + yyn] != nt)
            return goto_default [nt];

        return action_info [GOTO_INFO_OFFSET + yyn];
    }

    static inline int t_action (int state, int token)
    {
        const int yyn = action_index [state] + token;

        if (yyn < 0 || action_check [yyn] != token)
            return - action_default [state];

        return action_info [yyn];
    }
};


QT_END_NAMESPACE
#endif // GLSLPARSERTABLE_P_H

