######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 16 13:02:01 2007
######################################################################

TEMPLATE = app
TARGET=indenter
CONFIG += console

include(../indenter.pri)
SOURCES += main.cpp
